//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CarRentalLibrary.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Add {
            get {
                object obj = ResourceManager.GetObject("Add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Exit {
            get {
                object obj = ResourceManager.GetObject("Exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Print {
            get {
                object obj = ResourceManager.GetObject("Print", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap Search {
            get {
                object obj = ResourceManager.GetObject("Search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 INSERT INTO
        ///Back
        ///(
        ///LendID,
        ///Lender,
        ///BackDate
        ///)
        ///VALUES
        ///(
        ///?,
        ///?,
        ///?
        ///) 的本地化字符串。
        /// </summary>
        internal static string SQL_Insert_BackObject {
            get {
                return ResourceManager.GetString("SQL_Insert_BackObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 INSERT INTO
        ///Lend
        ///(
        ///LendID,
        ///Lender,
        ///PersonName,
        ///PersonID,
        ///PersonPhone,
        ///CarNumber,
        ///LendDate,
        ///BackDate,
        ///IsBack
        ///)
        ///VALUES
        ///(
        ///?,
        ///?,
        ///?,
        ///?,
        ///?,
        ///?,
        ///?,
        ///?,
        ///?
        ///) 的本地化字符串。
        /// </summary>
        internal static string SQL_Insert_LendObject {
            get {
                return ResourceManager.GetString("SQL_Insert_LendObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SELECT
        ///TOP {0}
        ///LendID,
        ///Lender,
        ///PersonName,
        ///PersonID,
        ///PersonPhone,
        ///CarNumber,
        ///LendDate,
        ///BackDate,
        ///IsBack
        ///FROM
        ///Lend
        ///ORDER BY
        ///LendDate DESC 的本地化字符串。
        /// </summary>
        internal static string SQL_Select_Lend_By_Top {
            get {
                return ResourceManager.GetString("SQL_Select_Lend_By_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UPDATE
        ///Lend
        ///SET
        ///LendID=?,
        ///Lender=?,
        ///PersonName=?,
        ///PersonID=?,
        ///PersonPhone=?,
        ///CarNumber=?,
        ///LendDate=?,
        ///BackDate=?,
        ///IsBack=?
        ///WHERE
        ///LendID=? 的本地化字符串。
        /// </summary>
        internal static string SQL_Update_Lend_By_LendID {
            get {
                return ResourceManager.GetString("SQL_Update_Lend_By_LendID", resourceCulture);
            }
        }
    }
}
